version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: f1
      MYSQL_ROOT_PASSWORD: spring
  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db


