version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: f1
      MYSQL_ROOT_PASSWORD: spring
  f1-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db


